// Generated by gencpp from file bwi_kr_execution/ComputeAllPlans.msg
// DO NOT EDIT!


#ifndef BWI_KR_EXECUTION_MESSAGE_COMPUTEALLPLANS_H
#define BWI_KR_EXECUTION_MESSAGE_COMPUTEALLPLANS_H

#include <ros/service_traits.h>


#include <bwi_kr_execution/ComputeAllPlansRequest.h>
#include <bwi_kr_execution/ComputeAllPlansResponse.h>


namespace bwi_kr_execution
{

struct ComputeAllPlans
{

typedef ComputeAllPlansRequest Request;
typedef ComputeAllPlansResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeAllPlans
} // namespace bwi_kr_execution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_kr_execution::ComputeAllPlans > {
  static const char* value()
  {
    return "5055d2fd937455d30a412653ffa463c6";
  }

  static const char* value(const ::bwi_kr_execution::ComputeAllPlans&) { return value(); }
};

template<>
struct DataType< ::bwi_kr_execution::ComputeAllPlans > {
  static const char* value()
  {
    return "bwi_kr_execution/ComputeAllPlans";
  }

  static const char* value(const ::bwi_kr_execution::ComputeAllPlans&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_kr_execution::ComputeAllPlansRequest> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::ComputeAllPlans > 
template<>
struct MD5Sum< ::bwi_kr_execution::ComputeAllPlansRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::ComputeAllPlans >::value();
  }
  static const char* value(const ::bwi_kr_execution::ComputeAllPlansRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::ComputeAllPlansRequest> should match 
// service_traits::DataType< ::bwi_kr_execution::ComputeAllPlans > 
template<>
struct DataType< ::bwi_kr_execution::ComputeAllPlansRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::ComputeAllPlans >::value();
  }
  static const char* value(const ::bwi_kr_execution::ComputeAllPlansRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_kr_execution::ComputeAllPlansResponse> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::ComputeAllPlans > 
template<>
struct MD5Sum< ::bwi_kr_execution::ComputeAllPlansResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::ComputeAllPlans >::value();
  }
  static const char* value(const ::bwi_kr_execution::ComputeAllPlansResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::ComputeAllPlansResponse> should match 
// service_traits::DataType< ::bwi_kr_execution::ComputeAllPlans > 
template<>
struct DataType< ::bwi_kr_execution::ComputeAllPlansResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::ComputeAllPlans >::value();
  }
  static const char* value(const ::bwi_kr_execution::ComputeAllPlansResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_KR_EXECUTION_MESSAGE_COMPUTEALLPLANS_H
