// Generated by gencpp from file bwi_kr_execution/CurrentStateQuery.msg
// DO NOT EDIT!


#ifndef BWI_KR_EXECUTION_MESSAGE_CURRENTSTATEQUERY_H
#define BWI_KR_EXECUTION_MESSAGE_CURRENTSTATEQUERY_H

#include <ros/service_traits.h>


#include <bwi_kr_execution/CurrentStateQueryRequest.h>
#include <bwi_kr_execution/CurrentStateQueryResponse.h>


namespace bwi_kr_execution
{

struct CurrentStateQuery
{

typedef CurrentStateQueryRequest Request;
typedef CurrentStateQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CurrentStateQuery
} // namespace bwi_kr_execution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_kr_execution::CurrentStateQuery > {
  static const char* value()
  {
    return "2cbc1d643059afa4b61504739724cdfc";
  }

  static const char* value(const ::bwi_kr_execution::CurrentStateQuery&) { return value(); }
};

template<>
struct DataType< ::bwi_kr_execution::CurrentStateQuery > {
  static const char* value()
  {
    return "bwi_kr_execution/CurrentStateQuery";
  }

  static const char* value(const ::bwi_kr_execution::CurrentStateQuery&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_kr_execution::CurrentStateQueryRequest> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::CurrentStateQuery > 
template<>
struct MD5Sum< ::bwi_kr_execution::CurrentStateQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::bwi_kr_execution::CurrentStateQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::CurrentStateQueryRequest> should match 
// service_traits::DataType< ::bwi_kr_execution::CurrentStateQuery > 
template<>
struct DataType< ::bwi_kr_execution::CurrentStateQueryRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::bwi_kr_execution::CurrentStateQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_kr_execution::CurrentStateQueryResponse> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::CurrentStateQuery > 
template<>
struct MD5Sum< ::bwi_kr_execution::CurrentStateQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::bwi_kr_execution::CurrentStateQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::CurrentStateQueryResponse> should match 
// service_traits::DataType< ::bwi_kr_execution::CurrentStateQuery > 
template<>
struct DataType< ::bwi_kr_execution::CurrentStateQueryResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::CurrentStateQuery >::value();
  }
  static const char* value(const ::bwi_kr_execution::CurrentStateQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_KR_EXECUTION_MESSAGE_CURRENTSTATEQUERY_H
