// Generated by gencpp from file bwi_kr_execution/IsPlanValid.msg
// DO NOT EDIT!


#ifndef BWI_KR_EXECUTION_MESSAGE_ISPLANVALID_H
#define BWI_KR_EXECUTION_MESSAGE_ISPLANVALID_H

#include <ros/service_traits.h>


#include <bwi_kr_execution/IsPlanValidRequest.h>
#include <bwi_kr_execution/IsPlanValidResponse.h>


namespace bwi_kr_execution
{

struct IsPlanValid
{

typedef IsPlanValidRequest Request;
typedef IsPlanValidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsPlanValid
} // namespace bwi_kr_execution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_kr_execution::IsPlanValid > {
  static const char* value()
  {
    return "80564b2371ef8008ffd47822957ab439";
  }

  static const char* value(const ::bwi_kr_execution::IsPlanValid&) { return value(); }
};

template<>
struct DataType< ::bwi_kr_execution::IsPlanValid > {
  static const char* value()
  {
    return "bwi_kr_execution/IsPlanValid";
  }

  static const char* value(const ::bwi_kr_execution::IsPlanValid&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_kr_execution::IsPlanValidRequest> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::IsPlanValid > 
template<>
struct MD5Sum< ::bwi_kr_execution::IsPlanValidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::IsPlanValid >::value();
  }
  static const char* value(const ::bwi_kr_execution::IsPlanValidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::IsPlanValidRequest> should match 
// service_traits::DataType< ::bwi_kr_execution::IsPlanValid > 
template<>
struct DataType< ::bwi_kr_execution::IsPlanValidRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::IsPlanValid >::value();
  }
  static const char* value(const ::bwi_kr_execution::IsPlanValidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_kr_execution::IsPlanValidResponse> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::IsPlanValid > 
template<>
struct MD5Sum< ::bwi_kr_execution::IsPlanValidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::IsPlanValid >::value();
  }
  static const char* value(const ::bwi_kr_execution::IsPlanValidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::IsPlanValidResponse> should match 
// service_traits::DataType< ::bwi_kr_execution::IsPlanValid > 
template<>
struct DataType< ::bwi_kr_execution::IsPlanValidResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::IsPlanValid >::value();
  }
  static const char* value(const ::bwi_kr_execution::IsPlanValidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_KR_EXECUTION_MESSAGE_ISPLANVALID_H
