// Generated by gencpp from file bwi_kr_execution/IsPlanValidRequest.msg
// DO NOT EDIT!


#ifndef BWI_KR_EXECUTION_MESSAGE_ISPLANVALIDREQUEST_H
#define BWI_KR_EXECUTION_MESSAGE_ISPLANVALIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bwi_kr_execution/AnswerSet.h>
#include <bwi_kr_execution/AspRule.h>

namespace bwi_kr_execution
{
template <class ContainerAllocator>
struct IsPlanValidRequest_
{
  typedef IsPlanValidRequest_<ContainerAllocator> Type;

  IsPlanValidRequest_()
    : plan()
    , goal()  {
    }
  IsPlanValidRequest_(const ContainerAllocator& _alloc)
    : plan(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::bwi_kr_execution::AnswerSet_<ContainerAllocator>  _plan_type;
  _plan_type plan;

   typedef std::vector< ::bwi_kr_execution::AspRule_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::bwi_kr_execution::AspRule_<ContainerAllocator> >::other >  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsPlanValidRequest_

typedef ::bwi_kr_execution::IsPlanValidRequest_<std::allocator<void> > IsPlanValidRequest;

typedef boost::shared_ptr< ::bwi_kr_execution::IsPlanValidRequest > IsPlanValidRequestPtr;
typedef boost::shared_ptr< ::bwi_kr_execution::IsPlanValidRequest const> IsPlanValidRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bwi_kr_execution

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'bwi_kr_execution': ['/home/jumper/Documents/bwi_my_ws/bwi_ws/src/bwi_common/bwi_kr_execution/msg', '/home/jumper/Documents/bwi_my_ws/bwi_ws/devel/share/bwi_kr_execution/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df6bb06058bbc88de7aec8eef2490a9e";
  }

  static const char* value(const ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf6bb06058bbc88dULL;
  static const uint64_t static_value2 = 0xe7aec8eef2490a9eULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_kr_execution/IsPlanValidRequest";
  }

  static const char* value(const ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AnswerSet plan\n\
AspRule[] goal\n\
\n\
================================================================================\n\
MSG: bwi_kr_execution/AnswerSet\n\
AspFluent[] fluents\n\
bool satisfied\n\
\n\
================================================================================\n\
MSG: bwi_kr_execution/AspFluent\n\
string name\n\
string[] variables\n\
uint32 timeStep\n\
\n\
================================================================================\n\
MSG: bwi_kr_execution/AspRule\n\
AspFluent[] head\n\
AspFluent[] body\n\
";
  }

  static const char* value(const ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsPlanValidRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_kr_execution::IsPlanValidRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan: ";
    s << std::endl;
    Printer< ::bwi_kr_execution::AnswerSet_<ContainerAllocator> >::stream(s, indent + "  ", v.plan);
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::bwi_kr_execution::AspRule_<ContainerAllocator> >::stream(s, indent + "    ", v.goal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_KR_EXECUTION_MESSAGE_ISPLANVALIDREQUEST_H
