// Generated by gencpp from file bwi_kr_execution/UpdateFluents.msg
// DO NOT EDIT!


#ifndef BWI_KR_EXECUTION_MESSAGE_UPDATEFLUENTS_H
#define BWI_KR_EXECUTION_MESSAGE_UPDATEFLUENTS_H

#include <ros/service_traits.h>


#include <bwi_kr_execution/UpdateFluentsRequest.h>
#include <bwi_kr_execution/UpdateFluentsResponse.h>


namespace bwi_kr_execution
{

struct UpdateFluents
{

typedef UpdateFluentsRequest Request;
typedef UpdateFluentsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateFluents
} // namespace bwi_kr_execution


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_kr_execution::UpdateFluents > {
  static const char* value()
  {
    return "227bd43e3dadc0cc21a93d12243f42ad";
  }

  static const char* value(const ::bwi_kr_execution::UpdateFluents&) { return value(); }
};

template<>
struct DataType< ::bwi_kr_execution::UpdateFluents > {
  static const char* value()
  {
    return "bwi_kr_execution/UpdateFluents";
  }

  static const char* value(const ::bwi_kr_execution::UpdateFluents&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_kr_execution::UpdateFluentsRequest> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::UpdateFluents > 
template<>
struct MD5Sum< ::bwi_kr_execution::UpdateFluentsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::UpdateFluents >::value();
  }
  static const char* value(const ::bwi_kr_execution::UpdateFluentsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::UpdateFluentsRequest> should match 
// service_traits::DataType< ::bwi_kr_execution::UpdateFluents > 
template<>
struct DataType< ::bwi_kr_execution::UpdateFluentsRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::UpdateFluents >::value();
  }
  static const char* value(const ::bwi_kr_execution::UpdateFluentsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_kr_execution::UpdateFluentsResponse> should match 
// service_traits::MD5Sum< ::bwi_kr_execution::UpdateFluents > 
template<>
struct MD5Sum< ::bwi_kr_execution::UpdateFluentsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_kr_execution::UpdateFluents >::value();
  }
  static const char* value(const ::bwi_kr_execution::UpdateFluentsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_kr_execution::UpdateFluentsResponse> should match 
// service_traits::DataType< ::bwi_kr_execution::UpdateFluents > 
template<>
struct DataType< ::bwi_kr_execution::UpdateFluentsResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_kr_execution::UpdateFluents >::value();
  }
  static const char* value(const ::bwi_kr_execution::UpdateFluentsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_KR_EXECUTION_MESSAGE_UPDATEFLUENTS_H
