# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bwi_virtour/GetTourStateRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetTourStateRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "bwi_virtour/GetTourStateRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetTourStateRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bwi_virtour/GetTourStateResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetTourStateResponse(genpy.Message):
  _md5sum = "948457c50757084326687f7ddb2305ee"
  _type = "bwi_virtour/GetTourStateResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool tourAllowed
bool tourInProgress
uint64 tourDuration
uint64 tourStartTime
uint64 lastPingTime
string tourLeader

"""
  __slots__ = ['tourAllowed','tourInProgress','tourDuration','tourStartTime','lastPingTime','tourLeader']
  _slot_types = ['bool','bool','uint64','uint64','uint64','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tourAllowed,tourInProgress,tourDuration,tourStartTime,lastPingTime,tourLeader

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetTourStateResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.tourAllowed is None:
        self.tourAllowed = False
      if self.tourInProgress is None:
        self.tourInProgress = False
      if self.tourDuration is None:
        self.tourDuration = 0
      if self.tourStartTime is None:
        self.tourStartTime = 0
      if self.lastPingTime is None:
        self.lastPingTime = 0
      if self.tourLeader is None:
        self.tourLeader = ''
    else:
      self.tourAllowed = False
      self.tourInProgress = False
      self.tourDuration = 0
      self.tourStartTime = 0
      self.lastPingTime = 0
      self.tourLeader = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B3Q.pack(_x.tourAllowed, _x.tourInProgress, _x.tourDuration, _x.tourStartTime, _x.lastPingTime))
      _x = self.tourLeader
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.tourAllowed, _x.tourInProgress, _x.tourDuration, _x.tourStartTime, _x.lastPingTime,) = _struct_2B3Q.unpack(str[start:end])
      self.tourAllowed = bool(self.tourAllowed)
      self.tourInProgress = bool(self.tourInProgress)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tourLeader = str[start:end].decode('utf-8')
      else:
        self.tourLeader = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B3Q.pack(_x.tourAllowed, _x.tourInProgress, _x.tourDuration, _x.tourStartTime, _x.lastPingTime))
      _x = self.tourLeader
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 26
      (_x.tourAllowed, _x.tourInProgress, _x.tourDuration, _x.tourStartTime, _x.lastPingTime,) = _struct_2B3Q.unpack(str[start:end])
      self.tourAllowed = bool(self.tourAllowed)
      self.tourInProgress = bool(self.tourInProgress)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tourLeader = str[start:end].decode('utf-8')
      else:
        self.tourLeader = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B3Q = struct.Struct("<2B3Q")
class GetTourState(object):
  _type          = 'bwi_virtour/GetTourState'
  _md5sum = '948457c50757084326687f7ddb2305ee'
  _request_class  = GetTourStateRequest
  _response_class = GetTourStateResponse
