# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from multi_level_map_msgs/ChangeCurrentLevelRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ChangeCurrentLevelRequest(genpy.Message):
  _md5sum = "ce4152574d0751ba62d82ab6e034d739"
  _type = "multi_level_map_msgs/ChangeCurrentLevelRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string new_level_id
bool publish_initial_pose
geometry_msgs/PoseWithCovarianceStamped initial_pose

================================================================================
MSG: geometry_msgs/PoseWithCovarianceStamped
# This expresses an estimated pose with a reference coordinate frame and timestamp

Header header
PoseWithCovariance pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['new_level_id','publish_initial_pose','initial_pose']
  _slot_types = ['string','bool','geometry_msgs/PoseWithCovarianceStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       new_level_id,publish_initial_pose,initial_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChangeCurrentLevelRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.new_level_id is None:
        self.new_level_id = ''
      if self.publish_initial_pose is None:
        self.publish_initial_pose = False
      if self.initial_pose is None:
        self.initial_pose = geometry_msgs.msg.PoseWithCovarianceStamped()
    else:
      self.new_level_id = ''
      self.publish_initial_pose = False
      self.initial_pose = geometry_msgs.msg.PoseWithCovarianceStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.new_level_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B3I.pack(_x.publish_initial_pose, _x.initial_pose.header.seq, _x.initial_pose.header.stamp.secs, _x.initial_pose.header.stamp.nsecs))
      _x = self.initial_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.initial_pose.pose.pose.position.x, _x.initial_pose.pose.pose.position.y, _x.initial_pose.pose.pose.position.z, _x.initial_pose.pose.pose.orientation.x, _x.initial_pose.pose.pose.orientation.y, _x.initial_pose.pose.pose.orientation.z, _x.initial_pose.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.initial_pose.pose.covariance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.initial_pose is None:
        self.initial_pose = geometry_msgs.msg.PoseWithCovarianceStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.new_level_id = str[start:end].decode('utf-8')
      else:
        self.new_level_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.publish_initial_pose, _x.initial_pose.header.seq, _x.initial_pose.header.stamp.secs, _x.initial_pose.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.publish_initial_pose = bool(self.publish_initial_pose)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.initial_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.initial_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.initial_pose.pose.pose.position.x, _x.initial_pose.pose.pose.position.y, _x.initial_pose.pose.pose.position.z, _x.initial_pose.pose.pose.orientation.x, _x.initial_pose.pose.pose.orientation.y, _x.initial_pose.pose.pose.orientation.z, _x.initial_pose.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.initial_pose.pose.covariance = _struct_36d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.new_level_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B3I.pack(_x.publish_initial_pose, _x.initial_pose.header.seq, _x.initial_pose.header.stamp.secs, _x.initial_pose.header.stamp.nsecs))
      _x = self.initial_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.initial_pose.pose.pose.position.x, _x.initial_pose.pose.pose.position.y, _x.initial_pose.pose.pose.position.z, _x.initial_pose.pose.pose.orientation.x, _x.initial_pose.pose.pose.orientation.y, _x.initial_pose.pose.pose.orientation.z, _x.initial_pose.pose.pose.orientation.w))
      buff.write(self.initial_pose.pose.covariance.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.initial_pose is None:
        self.initial_pose = geometry_msgs.msg.PoseWithCovarianceStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.new_level_id = str[start:end].decode('utf-8')
      else:
        self.new_level_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.publish_initial_pose, _x.initial_pose.header.seq, _x.initial_pose.header.stamp.secs, _x.initial_pose.header.stamp.nsecs,) = _struct_B3I.unpack(str[start:end])
      self.publish_initial_pose = bool(self.publish_initial_pose)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.initial_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.initial_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.initial_pose.pose.pose.position.x, _x.initial_pose.pose.pose.position.y, _x.initial_pose.pose.pose.position.z, _x.initial_pose.pose.pose.orientation.x, _x.initial_pose.pose.pose.orientation.y, _x.initial_pose.pose.pose.orientation.z, _x.initial_pose.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.initial_pose.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_36d = struct.Struct("<36d")
_struct_7d = struct.Struct("<7d")
_struct_B3I = struct.Struct("<B3I")
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from multi_level_map_msgs/ChangeCurrentLevelResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ChangeCurrentLevelResponse(genpy.Message):
  _md5sum = "6fe914479ce03184a758c3f6990c928f"
  _type = "multi_level_map_msgs/ChangeCurrentLevelResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool success
string error_message

"""
  __slots__ = ['success','error_message']
  _slot_types = ['bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,error_message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChangeCurrentLevelResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.error_message is None:
        self.error_message = ''
    else:
      self.success = False
      self.error_message = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.success))
      _x = self.error_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _struct_B.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_message = str[start:end].decode('utf-8')
      else:
        self.error_message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.success))
      _x = self.error_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.success,) = _struct_B.unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_message = str[start:end].decode('utf-8')
      else:
        self.error_message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
class ChangeCurrentLevel(object):
  _type          = 'multi_level_map_msgs/ChangeCurrentLevel'
  _md5sum = 'ea2e164e69b835c64629bde577a80f03'
  _request_class  = ChangeCurrentLevelRequest
  _response_class = ChangeCurrentLevelResponse
