; Auto-generated. Do not edit!


(cl:in-package bwi_msgs-msg)


;//! \htmlinclude LEDControlFeedback.msg.html

(cl:defclass <LEDControlFeedback> (roslisp-msg-protocol:ros-message)
  ((time_running
    :reader time_running
    :initarg :time_running
    :type cl:real
    :initform 0))
)

(cl:defclass LEDControlFeedback (<LEDControlFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LEDControlFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LEDControlFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_msgs-msg:<LEDControlFeedback> is deprecated: use bwi_msgs-msg:LEDControlFeedback instead.")))

(cl:ensure-generic-function 'time_running-val :lambda-list '(m))
(cl:defmethod time_running-val ((m <LEDControlFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bwi_msgs-msg:time_running-val is deprecated.  Use bwi_msgs-msg:time_running instead.")
  (time_running m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LEDControlFeedback>) ostream)
  "Serializes a message object of type '<LEDControlFeedback>"
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'time_running)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'time_running) (cl:floor (cl:slot-value msg 'time_running)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LEDControlFeedback>) istream)
  "Deserializes a message object of type '<LEDControlFeedback>"
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time_running) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LEDControlFeedback>)))
  "Returns string type for a message object of type '<LEDControlFeedback>"
  "bwi_msgs/LEDControlFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LEDControlFeedback)))
  "Returns string type for a message object of type 'LEDControlFeedback"
  "bwi_msgs/LEDControlFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LEDControlFeedback>)))
  "Returns md5sum for a message object of type '<LEDControlFeedback>"
  "75824f08f05571689ccf412bca8194f3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LEDControlFeedback)))
  "Returns md5sum for a message object of type 'LEDControlFeedback"
  "75824f08f05571689ccf412bca8194f3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LEDControlFeedback>)))
  "Returns full string definition for message of type '<LEDControlFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%duration time_running~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LEDControlFeedback)))
  "Returns full string definition for message of type 'LEDControlFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%duration time_running~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LEDControlFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LEDControlFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LEDControlFeedback
    (cl:cons ':time_running (time_running msg))
))
