; Auto-generated. Do not edit!


(cl:in-package bwi_msgs-msg)


;//! \htmlinclude LEDControlResult.msg.html

(cl:defclass <LEDControlResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:fixnum
    :initform 0)
   (status
    :reader status
    :initarg :status
    :type cl:string
    :initform ""))
)

(cl:defclass LEDControlResult (<LEDControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LEDControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LEDControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_msgs-msg:<LEDControlResult> is deprecated: use bwi_msgs-msg:LEDControlResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <LEDControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bwi_msgs-msg:result-val is deprecated.  Use bwi_msgs-msg:result instead.")
  (result m))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <LEDControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bwi_msgs-msg:status-val is deprecated.  Use bwi_msgs-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LEDControlResult>) ostream)
  "Serializes a message object of type '<LEDControlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LEDControlResult>) istream)
  "Deserializes a message object of type '<LEDControlResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result)) (cl:read-byte istream))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LEDControlResult>)))
  "Returns string type for a message object of type '<LEDControlResult>"
  "bwi_msgs/LEDControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LEDControlResult)))
  "Returns string type for a message object of type 'LEDControlResult"
  "bwi_msgs/LEDControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LEDControlResult>)))
  "Returns md5sum for a message object of type '<LEDControlResult>"
  "fdb8a9280351dc5483b6dd4488989352")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LEDControlResult)))
  "Returns md5sum for a message object of type 'LEDControlResult"
  "fdb8a9280351dc5483b6dd4488989352")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LEDControlResult>)))
  "Returns full string definition for message of type '<LEDControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint8 result~%string status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LEDControlResult)))
  "Returns full string definition for message of type 'LEDControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%uint8 result~%string status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LEDControlResult>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LEDControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LEDControlResult
    (cl:cons ':result (result msg))
    (cl:cons ':status (status msg))
))
