; Auto-generated. Do not edit!


(cl:in-package bwi_msgs-msg)


;//! \htmlinclude LEDControlGoal.msg.html

(cl:defclass <LEDControlGoal> (roslisp-msg-protocol:ros-message)
  ((type
    :reader type
    :initarg :type
    :type bwi_msgs-msg:LEDAnimations
    :initform (cl:make-instance 'bwi_msgs-msg:LEDAnimations))
   (timeout
    :reader timeout
    :initarg :timeout
    :type cl:real
    :initform 0))
)

(cl:defclass LEDControlGoal (<LEDControlGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LEDControlGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LEDControlGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_msgs-msg:<LEDControlGoal> is deprecated: use bwi_msgs-msg:LEDControlGoal instead.")))

(cl:ensure-generic-function 'type-val :lambda-list '(m))
(cl:defmethod type-val ((m <LEDControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bwi_msgs-msg:type-val is deprecated.  Use bwi_msgs-msg:type instead.")
  (type m))

(cl:ensure-generic-function 'timeout-val :lambda-list '(m))
(cl:defmethod timeout-val ((m <LEDControlGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bwi_msgs-msg:timeout-val is deprecated.  Use bwi_msgs-msg:timeout instead.")
  (timeout m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LEDControlGoal>) ostream)
  "Serializes a message object of type '<LEDControlGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'type) ostream)
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'timeout)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'timeout) (cl:floor (cl:slot-value msg 'timeout)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LEDControlGoal>) istream)
  "Deserializes a message object of type '<LEDControlGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'type) istream)
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'timeout) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LEDControlGoal>)))
  "Returns string type for a message object of type '<LEDControlGoal>"
  "bwi_msgs/LEDControlGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LEDControlGoal)))
  "Returns string type for a message object of type 'LEDControlGoal"
  "bwi_msgs/LEDControlGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LEDControlGoal>)))
  "Returns md5sum for a message object of type '<LEDControlGoal>"
  "7c6f8d9418a5dae69a9e986bc8673f77")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LEDControlGoal)))
  "Returns md5sum for a message object of type 'LEDControlGoal"
  "7c6f8d9418a5dae69a9e986bc8673f77")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LEDControlGoal>)))
  "Returns full string definition for message of type '<LEDControlGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bwi_msgs/LEDAnimations type~%duration timeout~%~%================================================================================~%MSG: bwi_msgs/LEDAnimations~%# LED Animations~%~%# Action Variables~%uint8 LEFT_TURN = 1~%uint8 RIGHT_TURN = 2~%uint8 REVERSE = 3~%uint8 BLOCKED = 4~%uint8 UP = 5~%uint8 DOWN = 6~%uint8 NEED_ASSIST = 7~%~%# Selects which animation to execute~%~%uint8 led_animations~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LEDControlGoal)))
  "Returns full string definition for message of type 'LEDControlGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bwi_msgs/LEDAnimations type~%duration timeout~%~%================================================================================~%MSG: bwi_msgs/LEDAnimations~%# LED Animations~%~%# Action Variables~%uint8 LEFT_TURN = 1~%uint8 RIGHT_TURN = 2~%uint8 REVERSE = 3~%uint8 BLOCKED = 4~%uint8 UP = 5~%uint8 DOWN = 6~%uint8 NEED_ASSIST = 7~%~%# Selects which animation to execute~%~%uint8 led_animations~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LEDControlGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'type))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LEDControlGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LEDControlGoal
    (cl:cons ':type (type msg))
    (cl:cons ':timeout (timeout msg))
))
