; Auto-generated. Do not edit!


(cl:in-package bwi_msgs-msg)


;//! \htmlinclude LogicalNavigationFeedback.msg.html

(cl:defclass <LogicalNavigationFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LogicalNavigationFeedback (<LogicalNavigationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LogicalNavigationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LogicalNavigationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_msgs-msg:<LogicalNavigationFeedback> is deprecated: use bwi_msgs-msg:LogicalNavigationFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LogicalNavigationFeedback>) ostream)
  "Serializes a message object of type '<LogicalNavigationFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LogicalNavigationFeedback>) istream)
  "Deserializes a message object of type '<LogicalNavigationFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LogicalNavigationFeedback>)))
  "Returns string type for a message object of type '<LogicalNavigationFeedback>"
  "bwi_msgs/LogicalNavigationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LogicalNavigationFeedback)))
  "Returns string type for a message object of type 'LogicalNavigationFeedback"
  "bwi_msgs/LogicalNavigationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LogicalNavigationFeedback>)))
  "Returns md5sum for a message object of type '<LogicalNavigationFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LogicalNavigationFeedback)))
  "Returns md5sum for a message object of type 'LogicalNavigationFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LogicalNavigationFeedback>)))
  "Returns full string definition for message of type '<LogicalNavigationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LogicalNavigationFeedback)))
  "Returns full string definition for message of type 'LogicalNavigationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LogicalNavigationFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LogicalNavigationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LogicalNavigationFeedback
))
