(cl:in-package segway_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MIN_PROPULSION_BATTERY_SOC-VAL
          MIN_PROPULSION_BATTERY_SOC
          MCU_BATTERY_SOC-VAL
          MCU_BATTERY_SOC
          MCU_BATTERY_TEMP_DEGC-VAL
          MCU_BATTERY_TEMP_DEGC
          MCU_INST_POWER_W-VAL
          MCU_INST_POWER_W
          MCU_TOTAL_ENERGY_WH-VAL
          MCU_TOTAL_ENERGY_WH
          MOTOR_CURRENT_A0PK-VAL
          MOTOR_CURRENT_A0PK
          MAX_MOTOR_CURRENT_A0PK-VAL
          MAX_MOTOR_CURRENT_A0PK
          MOTOR_CURRENT_LIMIT_A0PK-VAL
          MOTOR_CURRENT_LIMIT_A0PK
          MIN_MOTOR_CURRENT_LIMIT_A0PK-VAL
          MIN_MOTOR_CURRENT_LIMIT_A0PK
))