// Generated by gencpp from file segway_msgs/ConfigCmd.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_CONFIGCMD_H
#define SEGWAY_MSGS_MESSAGE_CONFIGCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace segway_msgs
{
template <class ContainerAllocator>
struct ConfigCmd_
{
  typedef ConfigCmd_<ContainerAllocator> Type;

  ConfigCmd_()
    : header()
    , gp_cmd()
    , gp_param(0)  {
    }
  ConfigCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gp_cmd(_alloc)
    , gp_param(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _gp_cmd_type;
  _gp_cmd_type gp_cmd;

   typedef uint32_t _gp_param_type;
  _gp_param_type gp_param;




  typedef boost::shared_ptr< ::segway_msgs::ConfigCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ConfigCmd_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigCmd_

typedef ::segway_msgs::ConfigCmd_<std::allocator<void> > ConfigCmd;

typedef boost::shared_ptr< ::segway_msgs::ConfigCmd > ConfigCmdPtr;
typedef boost::shared_ptr< ::segway_msgs::ConfigCmd const> ConfigCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ConfigCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ConfigCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segway_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'segway_msgs': ['/home/jumper/Documents/bwi_my_ws/bwi_ws/src/segway_v3/segway_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ConfigCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ConfigCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ConfigCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48e0d9e9ce5afb7e797ea6a1ab30254b";
  }

  static const char* value(const ::segway_msgs::ConfigCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48e0d9e9ce5afb7eULL;
  static const uint64_t static_value2 = 0x797ea6a1ab30254bULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ConfigCmd";
  }

  static const char* value(const ::segway_msgs::ConfigCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string gp_cmd\n\
uint32 gp_param\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::segway_msgs::ConfigCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gp_cmd);
      stream.next(m.gp_param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ConfigCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ConfigCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gp_cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.gp_cmd);
    s << indent << "gp_param: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.gp_param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_CONFIGCMD_H
