(cl:defpackage bwi_services-srv
  (:use )
  (:export
   "DELIVERMESSAGE"
   "<DELIVERMESSAGE-REQUEST>"
   "DELIVERMESSAGE-REQUEST"
   "<DELIVERMESSAGE-RESPONSE>"
   "DELIVERMESSAGE-RESPONSE"
   "GOTOLOCATION"
   "<GOTOLOCATION-REQUEST>"
   "GOTOLOCATION-REQUEST"
   "<GOTOLOCATION-RESPONSE>"
   "GOTOLOCATION-RESPONSE"
   "SPEAKMESSAGE"
   "<SPEAKMESSAGE-REQUEST>"
   "SPEAKMESSAGE-REQUEST"
   "<SPEAKMESSAGE-RESPONSE>"
   "SPEAKMESSAGE-RESPONSE"
  ))

