/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_HeaderFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_HeaderFS_h
#define __vtkGPUVolumeRayCastMapper_HeaderFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_HeaderFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_HeaderFS_h */
