/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS_h
#define __vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_MIPFourDependentNoCroppingFS_h */
