/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-6.3
 * 
 * Declare the vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS string.
 *
 */
#ifndef __vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS_h
#define __vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS_h

#include "vtkRenderingVolumeOpenGLModule.h"

VTKRENDERINGVOLUMEOPENGL_EXPORT extern const char *vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS;

#endif /* #ifndef __vtkGPUVolumeRayCastMapper_CompositeBinaryMaskFS_h */
