; Auto-generated. Do not edit!


(cl:in-package bwi_kr_execution-msg)


;//! \htmlinclude ExecutePlanGoal.msg.html

(cl:defclass <ExecutePlanGoal> (roslisp-msg-protocol:ros-message)
  ((aspGoal
    :reader aspGoal
    :initarg :aspGoal
    :type (cl:vector bwi_kr_execution-msg:AspRule)
   :initform (cl:make-array 0 :element-type 'bwi_kr_execution-msg:AspRule :initial-element (cl:make-instance 'bwi_kr_execution-msg:AspRule))))
)

(cl:defclass ExecutePlanGoal (<ExecutePlanGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutePlanGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutePlanGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_kr_execution-msg:<ExecutePlanGoal> is deprecated: use bwi_kr_execution-msg:ExecutePlanGoal instead.")))

(cl:ensure-generic-function 'aspGoal-val :lambda-list '(m))
(cl:defmethod aspGoal-val ((m <ExecutePlanGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bwi_kr_execution-msg:aspGoal-val is deprecated.  Use bwi_kr_execution-msg:aspGoal instead.")
  (aspGoal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutePlanGoal>) ostream)
  "Serializes a message object of type '<ExecutePlanGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'aspGoal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'aspGoal))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutePlanGoal>) istream)
  "Deserializes a message object of type '<ExecutePlanGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'aspGoal) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'aspGoal)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'bwi_kr_execution-msg:AspRule))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutePlanGoal>)))
  "Returns string type for a message object of type '<ExecutePlanGoal>"
  "bwi_kr_execution/ExecutePlanGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutePlanGoal)))
  "Returns string type for a message object of type 'ExecutePlanGoal"
  "bwi_kr_execution/ExecutePlanGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutePlanGoal>)))
  "Returns md5sum for a message object of type '<ExecutePlanGoal>"
  "2c9cb40febc2ce81b7684fa64b2f8111")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutePlanGoal)))
  "Returns md5sum for a message object of type 'ExecutePlanGoal"
  "2c9cb40febc2ce81b7684fa64b2f8111")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutePlanGoal>)))
  "Returns full string definition for message of type '<ExecutePlanGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%AspRule[] aspGoal~%~%================================================================================~%MSG: bwi_kr_execution/AspRule~%AspFluent[] head~%AspFluent[] body~%~%================================================================================~%MSG: bwi_kr_execution/AspFluent~%string name~%string[] variables~%uint32 timeStep~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutePlanGoal)))
  "Returns full string definition for message of type 'ExecutePlanGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%AspRule[] aspGoal~%~%================================================================================~%MSG: bwi_kr_execution/AspRule~%AspFluent[] head~%AspFluent[] body~%~%================================================================================~%MSG: bwi_kr_execution/AspFluent~%string name~%string[] variables~%uint32 timeStep~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutePlanGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'aspGoal) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutePlanGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutePlanGoal
    (cl:cons ':aspGoal (aspGoal msg))
))
