; Auto-generated. Do not edit!


(cl:in-package bwi_kr_execution-msg)


;//! \htmlinclude ExecutePlanResult.msg.html

(cl:defclass <ExecutePlanResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ExecutePlanResult (<ExecutePlanResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecutePlanResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecutePlanResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_kr_execution-msg:<ExecutePlanResult> is deprecated: use bwi_kr_execution-msg:ExecutePlanResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecutePlanResult>) ostream)
  "Serializes a message object of type '<ExecutePlanResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecutePlanResult>) istream)
  "Deserializes a message object of type '<ExecutePlanResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecutePlanResult>)))
  "Returns string type for a message object of type '<ExecutePlanResult>"
  "bwi_kr_execution/ExecutePlanResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecutePlanResult)))
  "Returns string type for a message object of type 'ExecutePlanResult"
  "bwi_kr_execution/ExecutePlanResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecutePlanResult>)))
  "Returns md5sum for a message object of type '<ExecutePlanResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecutePlanResult)))
  "Returns md5sum for a message object of type 'ExecutePlanResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecutePlanResult>)))
  "Returns full string definition for message of type '<ExecutePlanResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecutePlanResult)))
  "Returns full string definition for message of type 'ExecutePlanResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecutePlanResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecutePlanResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecutePlanResult
))
