// Generated by gencpp from file bwi_msgs/AvailableRobot.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_AVAILABLEROBOT_H
#define BWI_MSGS_MESSAGE_AVAILABLEROBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_msgs
{
template <class ContainerAllocator>
struct AvailableRobot_
{
  typedef AvailableRobot_<ContainerAllocator> Type;

  AvailableRobot_()
    : name()
    , type(0)  {
    }
  AvailableRobot_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _type_type;
  _type_type type;


    enum { SEGBOT = 1 };
     enum { SEGBOT_ARM = 2 };
     enum { TURTLEBOT = 3 };
 

  typedef boost::shared_ptr< ::bwi_msgs::AvailableRobot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::AvailableRobot_<ContainerAllocator> const> ConstPtr;

}; // struct AvailableRobot_

typedef ::bwi_msgs::AvailableRobot_<std::allocator<void> > AvailableRobot;

typedef boost::shared_ptr< ::bwi_msgs::AvailableRobot > AvailableRobotPtr;
typedef boost::shared_ptr< ::bwi_msgs::AvailableRobot const> AvailableRobotConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::AvailableRobot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'bwi_msgs': ['/home/jumper/Documents/bwi_my_ws/bwi_ws/src/bwi_common/bwi_msgs/msg', '/home/jumper/Documents/bwi_my_ws/bwi_ws/devel/share/bwi_msgs/msg'], 'bwi_planning_common': ['/home/jumper/Documents/bwi_my_ws/bwi_ws/src/bwi_common/bwi_planning_common/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::AvailableRobot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::AvailableRobot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::AvailableRobot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30fc6869415622f85eeb8ffa688c745a";
  }

  static const char* value(const ::bwi_msgs::AvailableRobot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30fc6869415622f8ULL;
  static const uint64_t static_value2 = 0x5eeb8ffa688c745aULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/AvailableRobot";
  }

  static const char* value(const ::bwi_msgs::AvailableRobot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The current list of robots supported in the BWI Ecosystem. In an ideal world, this functionality would be replaced\n\
# by the capabilities framework.\n\
\n\
int32 SEGBOT = 1\n\
int32 SEGBOT_ARM = 2\n\
int32 TURTLEBOT = 3\n\
\n\
string name\n\
int32 type\n\
";
  }

  static const char* value(const ::bwi_msgs::AvailableRobot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AvailableRobot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::AvailableRobot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::AvailableRobot_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_AVAILABLEROBOT_H
