// Generated by gencpp from file bwi_msgs/LEDControlGoal.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_LEDCONTROLGOAL_H
#define BWI_MSGS_MESSAGE_LEDCONTROLGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bwi_msgs/LEDAnimations.h>

namespace bwi_msgs
{
template <class ContainerAllocator>
struct LEDControlGoal_
{
  typedef LEDControlGoal_<ContainerAllocator> Type;

  LEDControlGoal_()
    : type()
    , timeout()  {
    }
  LEDControlGoal_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , timeout()  {
  (void)_alloc;
    }



   typedef  ::bwi_msgs::LEDAnimations_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef ros::Duration _timeout_type;
  _timeout_type timeout;




  typedef boost::shared_ptr< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LEDControlGoal_

typedef ::bwi_msgs::LEDControlGoal_<std::allocator<void> > LEDControlGoal;

typedef boost::shared_ptr< ::bwi_msgs::LEDControlGoal > LEDControlGoalPtr;
typedef boost::shared_ptr< ::bwi_msgs::LEDControlGoal const> LEDControlGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::LEDControlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'bwi_msgs': ['/home/jumper/Documents/bwi_my_ws/bwi_ws/src/bwi_common/bwi_msgs/msg', '/home/jumper/Documents/bwi_my_ws/bwi_ws/devel/share/bwi_msgs/msg'], 'bwi_planning_common': ['/home/jumper/Documents/bwi_my_ws/bwi_ws/src/bwi_common/bwi_planning_common/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c6f8d9418a5dae69a9e986bc8673f77";
  }

  static const char* value(const ::bwi_msgs::LEDControlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c6f8d9418a5dae6ULL;
  static const uint64_t static_value2 = 0x9a9e986bc8673f77ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/LEDControlGoal";
  }

  static const char* value(const ::bwi_msgs::LEDControlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
bwi_msgs/LEDAnimations type\n\
duration timeout\n\
\n\
================================================================================\n\
MSG: bwi_msgs/LEDAnimations\n\
# LED Animations\n\
\n\
# Action Variables\n\
uint8 LEFT_TURN = 1\n\
uint8 RIGHT_TURN = 2\n\
uint8 REVERSE = 3\n\
uint8 BLOCKED = 4\n\
uint8 UP = 5\n\
uint8 DOWN = 6\n\
uint8 NEED_ASSIST = 7\n\
\n\
# Selects which animation to execute\n\
\n\
uint8 led_animations\n\
";
  }

  static const char* value(const ::bwi_msgs::LEDControlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDControlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::LEDControlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::LEDControlGoal_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::bwi_msgs::LEDAnimations_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    s << indent << "timeout: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_LEDCONTROLGOAL_H
