// Generated by gencpp from file bwi_msgs/NextLocation.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_NEXTLOCATION_H
#define BWI_MSGS_MESSAGE_NEXTLOCATION_H

#include <ros/service_traits.h>


#include <bwi_msgs/NextLocationRequest.h>
#include <bwi_msgs/NextLocationResponse.h>


namespace bwi_msgs
{

struct NextLocation
{

typedef NextLocationRequest Request;
typedef NextLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NextLocation
} // namespace bwi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_msgs::NextLocation > {
  static const char* value()
  {
    return "7f666469cc7c83a848e9c8c747e8937f";
  }

  static const char* value(const ::bwi_msgs::NextLocation&) { return value(); }
};

template<>
struct DataType< ::bwi_msgs::NextLocation > {
  static const char* value()
  {
    return "bwi_msgs/NextLocation";
  }

  static const char* value(const ::bwi_msgs::NextLocation&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_msgs::NextLocationRequest> should match 
// service_traits::MD5Sum< ::bwi_msgs::NextLocation > 
template<>
struct MD5Sum< ::bwi_msgs::NextLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::NextLocation >::value();
  }
  static const char* value(const ::bwi_msgs::NextLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::NextLocationRequest> should match 
// service_traits::DataType< ::bwi_msgs::NextLocation > 
template<>
struct DataType< ::bwi_msgs::NextLocationRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::NextLocation >::value();
  }
  static const char* value(const ::bwi_msgs::NextLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_msgs::NextLocationResponse> should match 
// service_traits::MD5Sum< ::bwi_msgs::NextLocation > 
template<>
struct MD5Sum< ::bwi_msgs::NextLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::NextLocation >::value();
  }
  static const char* value(const ::bwi_msgs::NextLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::NextLocationResponse> should match 
// service_traits::DataType< ::bwi_msgs::NextLocation > 
template<>
struct DataType< ::bwi_msgs::NextLocationResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::NextLocation >::value();
  }
  static const char* value(const ::bwi_msgs::NextLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_MSGS_MESSAGE_NEXTLOCATION_H
