// Generated by gencpp from file bwi_msgs/ResolveChangeFloor.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_RESOLVECHANGEFLOOR_H
#define BWI_MSGS_MESSAGE_RESOLVECHANGEFLOOR_H

#include <ros/service_traits.h>


#include <bwi_msgs/ResolveChangeFloorRequest.h>
#include <bwi_msgs/ResolveChangeFloorResponse.h>


namespace bwi_msgs
{

struct ResolveChangeFloor
{

typedef ResolveChangeFloorRequest Request;
typedef ResolveChangeFloorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResolveChangeFloor
} // namespace bwi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_msgs::ResolveChangeFloor > {
  static const char* value()
  {
    return "d565d7d5ff83ae40abf53092bf5912c5";
  }

  static const char* value(const ::bwi_msgs::ResolveChangeFloor&) { return value(); }
};

template<>
struct DataType< ::bwi_msgs::ResolveChangeFloor > {
  static const char* value()
  {
    return "bwi_msgs/ResolveChangeFloor";
  }

  static const char* value(const ::bwi_msgs::ResolveChangeFloor&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_msgs::ResolveChangeFloorRequest> should match 
// service_traits::MD5Sum< ::bwi_msgs::ResolveChangeFloor > 
template<>
struct MD5Sum< ::bwi_msgs::ResolveChangeFloorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::ResolveChangeFloor >::value();
  }
  static const char* value(const ::bwi_msgs::ResolveChangeFloorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::ResolveChangeFloorRequest> should match 
// service_traits::DataType< ::bwi_msgs::ResolveChangeFloor > 
template<>
struct DataType< ::bwi_msgs::ResolveChangeFloorRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::ResolveChangeFloor >::value();
  }
  static const char* value(const ::bwi_msgs::ResolveChangeFloorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_msgs::ResolveChangeFloorResponse> should match 
// service_traits::MD5Sum< ::bwi_msgs::ResolveChangeFloor > 
template<>
struct MD5Sum< ::bwi_msgs::ResolveChangeFloorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::ResolveChangeFloor >::value();
  }
  static const char* value(const ::bwi_msgs::ResolveChangeFloorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::ResolveChangeFloorResponse> should match 
// service_traits::DataType< ::bwi_msgs::ResolveChangeFloor > 
template<>
struct DataType< ::bwi_msgs::ResolveChangeFloorResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::ResolveChangeFloor >::value();
  }
  static const char* value(const ::bwi_msgs::ResolveChangeFloorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_MSGS_MESSAGE_RESOLVECHANGEFLOOR_H
