// Generated by gencpp from file bwi_msgs/SaveImageResponse.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_SAVEIMAGERESPONSE_H
#define BWI_MSGS_MESSAGE_SAVEIMAGERESPONSE_H

#include <ros/service_traits.h>


#include <bwi_msgs/SaveImageResponseRequest.h>
#include <bwi_msgs/SaveImageResponseResponse.h>


namespace bwi_msgs
{

struct SaveImageResponse
{

typedef SaveImageResponseRequest Request;
typedef SaveImageResponseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveImageResponse
} // namespace bwi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_msgs::SaveImageResponse > {
  static const char* value()
  {
    return "a365655a2050358a4bc3505ffc1c4db3";
  }

  static const char* value(const ::bwi_msgs::SaveImageResponse&) { return value(); }
};

template<>
struct DataType< ::bwi_msgs::SaveImageResponse > {
  static const char* value()
  {
    return "bwi_msgs/SaveImageResponse";
  }

  static const char* value(const ::bwi_msgs::SaveImageResponse&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_msgs::SaveImageResponseRequest> should match 
// service_traits::MD5Sum< ::bwi_msgs::SaveImageResponse > 
template<>
struct MD5Sum< ::bwi_msgs::SaveImageResponseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::SaveImageResponse >::value();
  }
  static const char* value(const ::bwi_msgs::SaveImageResponseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::SaveImageResponseRequest> should match 
// service_traits::DataType< ::bwi_msgs::SaveImageResponse > 
template<>
struct DataType< ::bwi_msgs::SaveImageResponseRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::SaveImageResponse >::value();
  }
  static const char* value(const ::bwi_msgs::SaveImageResponseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_msgs::SaveImageResponseResponse> should match 
// service_traits::MD5Sum< ::bwi_msgs::SaveImageResponse > 
template<>
struct MD5Sum< ::bwi_msgs::SaveImageResponseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::SaveImageResponse >::value();
  }
  static const char* value(const ::bwi_msgs::SaveImageResponseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::SaveImageResponseResponse> should match 
// service_traits::DataType< ::bwi_msgs::SaveImageResponse > 
template<>
struct DataType< ::bwi_msgs::SaveImageResponseResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::SaveImageResponse >::value();
  }
  static const char* value(const ::bwi_msgs::SaveImageResponseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_MSGS_MESSAGE_SAVEIMAGERESPONSE_H
