// Generated by gencpp from file bwi_msgs/SemanticParser.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_SEMANTICPARSER_H
#define BWI_MSGS_MESSAGE_SEMANTICPARSER_H

#include <ros/service_traits.h>


#include <bwi_msgs/SemanticParserRequest.h>
#include <bwi_msgs/SemanticParserResponse.h>


namespace bwi_msgs
{

struct SemanticParser
{

typedef SemanticParserRequest Request;
typedef SemanticParserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SemanticParser
} // namespace bwi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_msgs::SemanticParser > {
  static const char* value()
  {
    return "12b95219baec3a9aff9fedb292061f4e";
  }

  static const char* value(const ::bwi_msgs::SemanticParser&) { return value(); }
};

template<>
struct DataType< ::bwi_msgs::SemanticParser > {
  static const char* value()
  {
    return "bwi_msgs/SemanticParser";
  }

  static const char* value(const ::bwi_msgs::SemanticParser&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_msgs::SemanticParserRequest> should match 
// service_traits::MD5Sum< ::bwi_msgs::SemanticParser > 
template<>
struct MD5Sum< ::bwi_msgs::SemanticParserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::SemanticParser >::value();
  }
  static const char* value(const ::bwi_msgs::SemanticParserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::SemanticParserRequest> should match 
// service_traits::DataType< ::bwi_msgs::SemanticParser > 
template<>
struct DataType< ::bwi_msgs::SemanticParserRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::SemanticParser >::value();
  }
  static const char* value(const ::bwi_msgs::SemanticParserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_msgs::SemanticParserResponse> should match 
// service_traits::MD5Sum< ::bwi_msgs::SemanticParser > 
template<>
struct MD5Sum< ::bwi_msgs::SemanticParserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::SemanticParser >::value();
  }
  static const char* value(const ::bwi_msgs::SemanticParserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::SemanticParserResponse> should match 
// service_traits::DataType< ::bwi_msgs::SemanticParser > 
template<>
struct DataType< ::bwi_msgs::SemanticParserResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::SemanticParser >::value();
  }
  static const char* value(const ::bwi_msgs::SemanticParserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_MSGS_MESSAGE_SEMANTICPARSER_H
