// Generated by gencpp from file bwi_msgs/Trigger.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_TRIGGER_H
#define BWI_MSGS_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <bwi_msgs/TriggerRequest.h>
#include <bwi_msgs/TriggerResponse.h>


namespace bwi_msgs
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace bwi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_msgs::Trigger > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::bwi_msgs::Trigger&) { return value(); }
};

template<>
struct DataType< ::bwi_msgs::Trigger > {
  static const char* value()
  {
    return "bwi_msgs/Trigger";
  }

  static const char* value(const ::bwi_msgs::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_msgs::TriggerRequest> should match 
// service_traits::MD5Sum< ::bwi_msgs::Trigger > 
template<>
struct MD5Sum< ::bwi_msgs::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::Trigger >::value();
  }
  static const char* value(const ::bwi_msgs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::TriggerRequest> should match 
// service_traits::DataType< ::bwi_msgs::Trigger > 
template<>
struct DataType< ::bwi_msgs::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::Trigger >::value();
  }
  static const char* value(const ::bwi_msgs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_msgs::TriggerResponse> should match 
// service_traits::MD5Sum< ::bwi_msgs::Trigger > 
template<>
struct MD5Sum< ::bwi_msgs::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_msgs::Trigger >::value();
  }
  static const char* value(const ::bwi_msgs::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_msgs::TriggerResponse> should match 
// service_traits::DataType< ::bwi_msgs::Trigger > 
template<>
struct DataType< ::bwi_msgs::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_msgs::Trigger >::value();
  }
  static const char* value(const ::bwi_msgs::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_MSGS_MESSAGE_TRIGGER_H
