// Generated by gencpp from file bwi_services/GoToLocationRequest.msg
// DO NOT EDIT!


#ifndef BWI_SERVICES_MESSAGE_GOTOLOCATIONREQUEST_H
#define BWI_SERVICES_MESSAGE_GOTOLOCATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_services
{
template <class ContainerAllocator>
struct GoToLocationRequest_
{
  typedef GoToLocationRequest_<ContainerAllocator> Type;

  GoToLocationRequest_()
    : location()  {
    }
  GoToLocationRequest_(const ContainerAllocator& _alloc)
    : location(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _location_type;
  _location_type location;




  typedef boost::shared_ptr< ::bwi_services::GoToLocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_services::GoToLocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoToLocationRequest_

typedef ::bwi_services::GoToLocationRequest_<std::allocator<void> > GoToLocationRequest;

typedef boost::shared_ptr< ::bwi_services::GoToLocationRequest > GoToLocationRequestPtr;
typedef boost::shared_ptr< ::bwi_services::GoToLocationRequest const> GoToLocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_services::GoToLocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bwi_services

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_services::GoToLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_services::GoToLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_services::GoToLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03da474bc61cfeb81a8854b4ca05bafa";
  }

  static const char* value(const ::bwi_services::GoToLocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03da474bc61cfeb8ULL;
  static const uint64_t static_value2 = 0x1a8854b4ca05bafaULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_services/GoToLocationRequest";
  }

  static const char* value(const ::bwi_services::GoToLocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string location\n\
";
  }

  static const char* value(const ::bwi_services::GoToLocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoToLocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_services::GoToLocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_services::GoToLocationRequest_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_SERVICES_MESSAGE_GOTOLOCATIONREQUEST_H
