// Generated by gencpp from file bwi_virtour/GetTourState.msg
// DO NOT EDIT!


#ifndef BWI_VIRTOUR_MESSAGE_GETTOURSTATE_H
#define BWI_VIRTOUR_MESSAGE_GETTOURSTATE_H

#include <ros/service_traits.h>


#include <bwi_virtour/GetTourStateRequest.h>
#include <bwi_virtour/GetTourStateResponse.h>


namespace bwi_virtour
{

struct GetTourState
{

typedef GetTourStateRequest Request;
typedef GetTourStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTourState
} // namespace bwi_virtour


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_virtour::GetTourState > {
  static const char* value()
  {
    return "948457c50757084326687f7ddb2305ee";
  }

  static const char* value(const ::bwi_virtour::GetTourState&) { return value(); }
};

template<>
struct DataType< ::bwi_virtour::GetTourState > {
  static const char* value()
  {
    return "bwi_virtour/GetTourState";
  }

  static const char* value(const ::bwi_virtour::GetTourState&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_virtour::GetTourStateRequest> should match 
// service_traits::MD5Sum< ::bwi_virtour::GetTourState > 
template<>
struct MD5Sum< ::bwi_virtour::GetTourStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_virtour::GetTourState >::value();
  }
  static const char* value(const ::bwi_virtour::GetTourStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_virtour::GetTourStateRequest> should match 
// service_traits::DataType< ::bwi_virtour::GetTourState > 
template<>
struct DataType< ::bwi_virtour::GetTourStateRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_virtour::GetTourState >::value();
  }
  static const char* value(const ::bwi_virtour::GetTourStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_virtour::GetTourStateResponse> should match 
// service_traits::MD5Sum< ::bwi_virtour::GetTourState > 
template<>
struct MD5Sum< ::bwi_virtour::GetTourStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_virtour::GetTourState >::value();
  }
  static const char* value(const ::bwi_virtour::GetTourStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_virtour::GetTourStateResponse> should match 
// service_traits::DataType< ::bwi_virtour::GetTourState > 
template<>
struct DataType< ::bwi_virtour::GetTourStateResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_virtour::GetTourState >::value();
  }
  static const char* value(const ::bwi_virtour::GetTourStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_VIRTOUR_MESSAGE_GETTOURSTATE_H
