// Generated by gencpp from file bwi_virtour/GoToLocation.msg
// DO NOT EDIT!


#ifndef BWI_VIRTOUR_MESSAGE_GOTOLOCATION_H
#define BWI_VIRTOUR_MESSAGE_GOTOLOCATION_H

#include <ros/service_traits.h>


#include <bwi_virtour/GoToLocationRequest.h>
#include <bwi_virtour/GoToLocationResponse.h>


namespace bwi_virtour
{

struct GoToLocation
{

typedef GoToLocationRequest Request;
typedef GoToLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoToLocation
} // namespace bwi_virtour


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_virtour::GoToLocation > {
  static const char* value()
  {
    return "d57678ae7c2e3a4ad7890b2341b74c06";
  }

  static const char* value(const ::bwi_virtour::GoToLocation&) { return value(); }
};

template<>
struct DataType< ::bwi_virtour::GoToLocation > {
  static const char* value()
  {
    return "bwi_virtour/GoToLocation";
  }

  static const char* value(const ::bwi_virtour::GoToLocation&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_virtour::GoToLocationRequest> should match 
// service_traits::MD5Sum< ::bwi_virtour::GoToLocation > 
template<>
struct MD5Sum< ::bwi_virtour::GoToLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_virtour::GoToLocation >::value();
  }
  static const char* value(const ::bwi_virtour::GoToLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_virtour::GoToLocationRequest> should match 
// service_traits::DataType< ::bwi_virtour::GoToLocation > 
template<>
struct DataType< ::bwi_virtour::GoToLocationRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_virtour::GoToLocation >::value();
  }
  static const char* value(const ::bwi_virtour::GoToLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_virtour::GoToLocationResponse> should match 
// service_traits::MD5Sum< ::bwi_virtour::GoToLocation > 
template<>
struct MD5Sum< ::bwi_virtour::GoToLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_virtour::GoToLocation >::value();
  }
  static const char* value(const ::bwi_virtour::GoToLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_virtour::GoToLocationResponse> should match 
// service_traits::DataType< ::bwi_virtour::GoToLocation > 
template<>
struct DataType< ::bwi_virtour::GoToLocationResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_virtour::GoToLocation >::value();
  }
  static const char* value(const ::bwi_virtour::GoToLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_VIRTOUR_MESSAGE_GOTOLOCATION_H
