// Generated by gencpp from file bwi_virtour/RequestTourRequest.msg
// DO NOT EDIT!


#ifndef BWI_VIRTOUR_MESSAGE_REQUESTTOURREQUEST_H
#define BWI_VIRTOUR_MESSAGE_REQUESTTOURREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_virtour
{
template <class ContainerAllocator>
struct RequestTourRequest_
{
  typedef RequestTourRequest_<ContainerAllocator> Type;

  RequestTourRequest_()
    : user()  {
    }
  RequestTourRequest_(const ContainerAllocator& _alloc)
    : user(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _user_type;
  _user_type user;




  typedef boost::shared_ptr< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestTourRequest_

typedef ::bwi_virtour::RequestTourRequest_<std::allocator<void> > RequestTourRequest;

typedef boost::shared_ptr< ::bwi_virtour::RequestTourRequest > RequestTourRequestPtr;
typedef boost::shared_ptr< ::bwi_virtour::RequestTourRequest const> RequestTourRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_virtour::RequestTourRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bwi_virtour

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "334ea0b9dd53b20b1554937c6dd08782";
  }

  static const char* value(const ::bwi_virtour::RequestTourRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x334ea0b9dd53b20bULL;
  static const uint64_t static_value2 = 0x1554937c6dd08782ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_virtour/RequestTourRequest";
  }

  static const char* value(const ::bwi_virtour::RequestTourRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user\n\
";
  }

  static const char* value(const ::bwi_virtour::RequestTourRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestTourRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_virtour::RequestTourRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_virtour::RequestTourRequest_<ContainerAllocator>& v)
  {
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.user);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_VIRTOUR_MESSAGE_REQUESTTOURREQUEST_H
