// Generated by gencpp from file bwi_virtour/RequestTour.msg
// DO NOT EDIT!


#ifndef BWI_VIRTOUR_MESSAGE_REQUESTTOUR_H
#define BWI_VIRTOUR_MESSAGE_REQUESTTOUR_H

#include <ros/service_traits.h>


#include <bwi_virtour/RequestTourRequest.h>
#include <bwi_virtour/RequestTourResponse.h>


namespace bwi_virtour
{

struct RequestTour
{

typedef RequestTourRequest Request;
typedef RequestTourResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestTour
} // namespace bwi_virtour


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bwi_virtour::RequestTour > {
  static const char* value()
  {
    return "ecb5124ad29672c457aff7f5cfe2dea1";
  }

  static const char* value(const ::bwi_virtour::RequestTour&) { return value(); }
};

template<>
struct DataType< ::bwi_virtour::RequestTour > {
  static const char* value()
  {
    return "bwi_virtour/RequestTour";
  }

  static const char* value(const ::bwi_virtour::RequestTour&) { return value(); }
};


// service_traits::MD5Sum< ::bwi_virtour::RequestTourRequest> should match 
// service_traits::MD5Sum< ::bwi_virtour::RequestTour > 
template<>
struct MD5Sum< ::bwi_virtour::RequestTourRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_virtour::RequestTour >::value();
  }
  static const char* value(const ::bwi_virtour::RequestTourRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_virtour::RequestTourRequest> should match 
// service_traits::DataType< ::bwi_virtour::RequestTour > 
template<>
struct DataType< ::bwi_virtour::RequestTourRequest>
{
  static const char* value()
  {
    return DataType< ::bwi_virtour::RequestTour >::value();
  }
  static const char* value(const ::bwi_virtour::RequestTourRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bwi_virtour::RequestTourResponse> should match 
// service_traits::MD5Sum< ::bwi_virtour::RequestTour > 
template<>
struct MD5Sum< ::bwi_virtour::RequestTourResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bwi_virtour::RequestTour >::value();
  }
  static const char* value(const ::bwi_virtour::RequestTourResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bwi_virtour::RequestTourResponse> should match 
// service_traits::DataType< ::bwi_virtour::RequestTour > 
template<>
struct DataType< ::bwi_virtour::RequestTourResponse>
{
  static const char* value()
  {
    return DataType< ::bwi_virtour::RequestTour >::value();
  }
  static const char* value(const ::bwi_virtour::RequestTourResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BWI_VIRTOUR_MESSAGE_REQUESTTOUR_H
