/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-6.3
 * 
 * Declare the vtkSurfaceLICPainter_SC string.
 *
 */
#ifndef __vtkSurfaceLICPainter_SC_h
#define __vtkSurfaceLICPainter_SC_h

#include "vtkRenderingLICModule.h"

VTKRENDERINGLIC_EXPORT extern const char *vtkSurfaceLICPainter_SC;

#endif /* #ifndef __vtkSurfaceLICPainter_SC_h */
