# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bwi_msgs/LEDAnimations.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LEDAnimations(genpy.Message):
  _md5sum = "d7b2a068392ac708121e3251cf2dde04"
  _type = "bwi_msgs/LEDAnimations"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# LED Animations

# Action Variables
uint8 LEFT_TURN = 1
uint8 RIGHT_TURN = 2
uint8 REVERSE = 3
uint8 BLOCKED = 4
uint8 UP = 5
uint8 DOWN = 6
uint8 NEED_ASSIST = 7

# Selects which animation to execute

uint8 led_animations"""
  # Pseudo-constants
  LEFT_TURN = 1
  RIGHT_TURN = 2
  REVERSE = 3
  BLOCKED = 4
  UP = 5
  DOWN = 6
  NEED_ASSIST = 7

  __slots__ = ['led_animations']
  _slot_types = ['uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       led_animations

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LEDAnimations, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.led_animations is None:
        self.led_animations = 0
    else:
      self.led_animations = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.led_animations))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.led_animations,) = _struct_B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.led_animations))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.led_animations,) = _struct_B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
